[package]
name = "craftflow-nbt"
version = "1.0.0"
edition = "2021"
description = "A serde-based NBT (from Minecraft) binary format implementation"
repository = "https://github.com/PonasKovas/craftflow/tree/master/craftflow-nbt"
license = "GPL-3.0-only"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
cesu8 = { workspace = true }
