[package]
name = "craftflow-nbt"
version = "3.0.0"
edition = "2021"
description = "A zero-copy NBT (from Minecraft) binary format implementation"
repository = "https://github.com/PonasKovas/craftflow/tree/master/craftflow-nbt"
license = "MPL-2.0"

[dependencies]
thiserror = { workspace = true }
simd_cesu8 = { workspace = true }
bytes = { workspace = true }
bytemuck = { workspace = true }
typenum = "1.18.0"
generic-array = "1.2.0"
