[package]
name = "craftflow"
version = "0.1.0"
edition = "2021"

[dependencies]
craftflow-protocol-versions = { path = "../craftflow-protocol-versions" }
craftflow-protocol-abstract = { path = "../craftflow-protocol-abstract" }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
aes = { workspace = true }
cfb8 = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
