[workspace]
members = ["craftflow", "craftflow-protocol", "example", "modules/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
byteorder = "1.5.0"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes = "0.8.4"
cfb8 = "0.8.1"
flate2 = "1.0.33"
tracing-subscriber = "0.3.18"
base64 = "0.22.1"
futures = "0.3.30"
ron = "0.8"
toml = "0.8"
proc-macro2 = "1.0"
quote = "1.0"
indexmap = { version = "2.5", features = ["serde"] }
thiserror = "1.0"
crab_nbt = { version = "0.2.1", features = ["serde"] }
