[package]
name = "closureslop-macros"
version = "0.1.0"
edition = "2024"

[lib]
doc = false       # https://github.com/rust-lang/cargo/issues/10368
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[lints]
workspace = true