[package]
name = "craftflow-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
