[package]
name = "craftflow-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
craftflow-nbt = { path = "../craftflow-nbt" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
maxlen = { path = "../../maxlen/" }