[package]
name = "craftflow-protocol-versions"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
git2 = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
