[package]
name = "craftflow-protocol-versions"
version = "0.1.0"
edition = "2021"

[dependencies]
craftflow-nbt = { path = "../craftflow-nbt" }
craftflow-protocol-core = { path = "../craftflow-protocol-core" }
shallowclone = { path = "../shallowclone" }
serde = { workspace = true }
