[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
craftflow = { path = "../../craftflow/" }
craftflow-protocol = { path = "../../craftflow-protocol/" }
tracing.workspace = true
tokio.workspace = true

[lints]
workspace = true