[package]
name = "closureslop"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.6.5"
smallbox = { workspace = true }

[dev-dependencies]
pollster = { version = "0.4.0", features = ["macro"] }
