[package]
name = "shallowclone"
version = "0.1.0"
edition = "2021"

[dependencies]
shallowclone-derive = { path = "../shallowclone-derive/" }

indexmap = { workspace = true, optional = true }

[features]
indexmap = ["dep:indexmap"]
